    - name: Check if c-states is configured 
      lineinfile:
        backup: true
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT=".*processor.max_cstate=1 intel_idle.max_cstate=0'
        state: absent
      check_mode: true
      register: grub_cmdline_check
      changed_when: false

    - name: Setting c-states >Reboot will be performed< (Skipping if already configured)
      lineinfile:
          backrefs: true
          path: /etc/default/grub
          regexp: "^(GRUB_CMDLINE_LINUX_DEFAULT=\".*)\"$"
          line: '\1 processor.max_cstate=1 intel_idle.max_cstate=0"'
      when: grub_cmdline_check.found == 0
      notify: 
        - update_grub
        - reboot-host
    
    - name: Show current boot config   
      debug:
        msg:
          - "{{ ansible_facts['cmdline'] }}"

    - name: Flush handlers
      meta: flush_handlers

    - name: Collect facts
      setup:

    - name: Show current boot config   
      debug:
        msg: "{{ ansible_facts['cmdline'] }}"           